require("options")
require("terminal")
require("keymaps")
require("lspconfig")

require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.colorscheme")
require("plugins.which-key")
require("plugins.tabline")
require("plugins.snippets")
